FROM python:3.10-slim

# NO USE THE COPY COMMAND INTO THE DOCKER FILE
# ONLY ADD ADDITIONAL DEPENDENCY ONE BY ONE
RUN pip install pytest
RUN pip install pandas
RUN pip install numpy
RUN pip install scikit-learn
